<?xml version="1.0" encoding="utf-8"?><Database Name="QWritev2" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=Pixcilelab;Initial Catalog=QWritev2;Integrated Security=True" SettingsObjectName="ExcelToSqlDataEntry.Properties.Settings" SettingsPropertyName="QWritev2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Class" Member="Classes">
    <Type Name="Class">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClassName" Type="System.String" DbType="NVarChar(1500) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SchoolId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Class_Student" Member="Students" ThisKey="Id" OtherKey="ClassId" Type="Student" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="DeviceId" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ClassId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoginId" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="FatherName" Type="System.String" DbType="NVarChar(1600)" CanBeNull="true" />
      <Association Name="Class_Student" Member="Class" ThisKey="ClassId" OtherKey="Id" Type="Class" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>